-- -----------------------------------------------------------------------------
-- Cooldowns
-- Author: OwnLight,
-- Created: Oct 12, 2018
--
-- Data.lua
-- -----------------------------------------------------------------------------
--
-- To all you helpful individuals who romp in here to add things
-- on your own, thank you.
--
-- I'm sorry my updates overwrite your changes and you have to constantly
-- backup this file or ignore updates in order to keep your version working.
--
-- If you'd like to submit a pull request on GitHub, I'd happily take a look.
--
--      https://github.com/inimicus/cooldowns
--
-- Here is some information that might be helpful:
--
-- Debugging/Finding IDs:
-- When finding information about new sets, you can get chat log spammed with
-- information about every EVENT_COMBAT_EVENT by typing in game chat:
--
--      /cool all on
--
-- You'll get spammed with all the abilities in chat. There might even be
-- a similar debug for effects commented somewhere else in the code, too.
--
-- Proc your set/synergy/whatever, then look for it in the chat. You'll get
-- the name, the ID, and the result. Take note of these values and then add
-- them to the Sets table below along with any other values needed.
--
-- Turn off chat spam with:
--
--      /cool all off
--
-- Easy as that.
--
-- Cool.Data.Sets (table):
-- This table contains all the set, synergy, and passive information that
-- the addon uses. But you probably already knew that.
--
-- Each entry is stored in a table with its key being the string name
-- of the set to track. Because of this, non-English clients don't work.
--
-- There are plans to implement better tracking that doesn't use the set name
-- and there is already a new branch on GitHub to track efforts there. But it
-- is quite a bit out of date, unfortunately.
--
-- Big thanks to Baertram for helping out on multi-language support.
--
-- Configuration Options:
--
-- * procType (string):     One of "set", "synergy", or "passive" to indicate
--                          what kind of tracking it is. Duhhhhh.
--
-- * event (number):        What kind of action identifies the proc happened.
--                          Generally this is EVENT_COMBAT_EVENT or 131102, but
--                          some other values do exist (Wyrd Tree, others).
--
-- * description (string):  Cosmetic. Adds a description to the tooltip.
--
-- * settingsColor (string):    Color in hex. Used to be used for the colors
--                              for each set in the settings menu, but since
--                              the menu was updated they aren't used. Will
--                              probably clean them up at some point.
--
-- * id (number | array):   The ID that identifies the proc condition.
--                          This can also be an array of numbers for proc
--                          conditions that span multiple IDs (Perfected/Non,
--                          synergies, stupid Pirate Skelly, and more).
--
-- * enabled (bool):        Used to identify if tracking and display are enabled.
--                          This is different from if the set is enabled in the
--                          settings. That's a different value stored in savedvars.
--                          This value is pointless here and will probably be
--                          removed in the future.
--
-- * result (number):       The result of the proc. These are numeric, defined
--                          in the table using their constants. When debugging,
--                          the number will appear instead of the constant name,
--                          so refer to the constants section below to match.
--
-- * cooldownDurationMs (number):   Number in milliseconds for the cooldown.
--                                  e.g. 30 seconds is 30000
--
-- * onCooldown (bool):     If the set is on cooldown.
--                          This is also pointless here and will
--                          probably be removed in the future.
--
-- * timeOfProc (number):   Time that the proc happened, used in maths to
--                          provide the countdown and cooldown time remaining.
--                          Pointless here, will be removed in the future.
--
-- * texture (string):      The path to the texture to use for the cooldown
--                          display. You can find textures with the TextureIt
--                          addon (though what's there is largely out of date)
--                          or via the method `/script d(GetAbilityIcon(ID))`.
--                          I just generally use any icon that doesn't
--                          look like ass. A lot look like ass.
--
-- * showFrame (bool):      Enables or disables showing the frame around
--                          the icon. Not used for monster helm icons.
--                          But most monster helm icons look like ass.
--
-- Constants:
--
-- Reference this section to make sense of what result and event numbers in
-- debug messages mean.
--
-- Results:
-- ACTION_RESULT_DAMAGE                 = 1
-- ACTION_RESULT_POWER_ENERGIZE         = 128
-- ACTION_RESULT_HEAL                   = 16
-- ACTION_RESULT_EFFECT_GAINED          = 2240 - The most common
-- ACTION_RESULT_EFFECT_GAINED_DURATION = 2245 - Use 2240 if both show up
-- ACTION_RESULT_ABILITY_ON_COOLDOWN    = 2080

-- Events:
-- EVENT_ABILITY_COOLDOWN_UPDATED       = 131181
-- EVENT_COMBAT_EVENT                   = 131102
-- EVENT_EFFECT_CHANGED                 = 131150
--
-- -----------------------------------------------------------------------------

Cool.Data = {}

-- Detect Perfect versions
-- Note: Trailing space!
Cool.Data.PerfectString = {
    "Perfected ",
    "Perfect ",
}
Cool.Data.Sets = {
------------ Sets ------------
	["Ironblood"] = {
	    procType = "set",
	    event = EVENT_COMBAT_EVENT,
	    description = "here you go fried",
	    settingsColor = "CD5031",
	    id = 97627,
	    enabled = false,
	    result = ACTION_RESULT_EFFECT_GAINED,
	    cooldownDurationMs = 15000,
	    onCooldown = false,
	    timeOfProc = 0,
	    texture = "/esoui/art/icons/u15dlc_bullet_5220.dds",
	    showFrame = true,
	    durationms = 10000,
	    stacks = nil,
		},
    ["Way of Martial Knowledge"] = {
	    procType = "set",
	    event = EVENT_COMBAT_EVENT,
	    description = "Displays when the MK proc is on the boss then its cooldown until it is ready again.",
	    settingsColor = "ff7800",
	    id = 127070,
	    enabled = false,
	    result = ACTION_RESULT_EFFECT_GAINED,
	    cooldownDurationMs = 8000,
	    onCooldown = false,
	    timeOfProc = 0,
	    texture = "/esoui/art/icons/ability_ava_005.dds",
	    showFrame = true,
	    durationms = 5000,
	    stacks = nil,
		},
    ["Burning Spellweave"] = {
	    procType = "set",
	    event = EVENT_COMBAT_EVENT,
	    description = "Displays when the BSW proc is available or cooldown until it is ready again.",
	    settingsColor = "df4242",
	    id = 61459,
	    enabled = false,
	    result = ACTION_RESULT_EFFECT_GAINED_DURATION,
	    cooldownDurationMs = 12000,
	    onCooldown = false,
	    timeOfProc = 0,
	    texture = "/esoui/art/icons/ability_destructionstaff_007.dds",
	    showFrame = true,
	    durationms = 8000,
	    stacks = nil,
		},
    ["Magicka Furnace"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Magicka Furnace proc is available or cooldown until it is ready again.",
        settingsColor = "3A97CF",
        id = 34813,
        enabled = false,
        result = ACTION_RESULT_POWER_ENERGIZE,
        cooldownDurationMs = 30000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/champion/champion_points_magicka_icon-hud.dds",
        showFrame = false,
	    durationms = 0,
	    stacks = nil,
		},
    ["Scathing Mage"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Scathing Mage proc is available or cooldown until it is ready again.",
        settingsColor = "3A97CF",
        id = 67288,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 5000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/LuiExtended/media/icons/abilities/ability_set_scathing_mage.dds",
        showFrame = true,
	durationms = 5000,
	stacks = nil,
	},
    ["Wyrd Tree's Blessing"] = {
        procType = "set",
        event = EVENT_ABILITY_COOLDOWN_UPDATED,
        description = "Displays when the Wyrd Tree proc is available or cooldown until it is ready again.",
        settingsColor = "FCFCCB",
        id = 34871,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 15000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_ava_005.dds",
        showFrame = true,
	durationms = 0,
	stacks = nil,
	},
    ["Vestments of the Warlock"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Magicka Flood proc is available or cooldown until it is ready again.",
        settingsColor = "3A97CF",
        id = 57163,
        enabled = false,
        result = ACTION_RESULT_POWER_ENERGIZE,
        cooldownDurationMs = 45000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/champion/champion_points_magicka_icon-hud.dds",
        showFrame = false,
		durationms = 0,
		stacks = nil,
		},
    ["Trappings of Invigoration"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the stamina return proc is available or cooldown until it is ready again.",
        settingsColor = "92C843",
        id = 101970,
        enabled = false,
        result = ACTION_RESULT_POWER_ENERGIZE,
        cooldownDurationMs = 45000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/champion/champion_points_stamina_icon-hud.dds",
        showFrame = false,
		durationms = 0,
		stacks = nil,
		},
    ["Shroud of the Lich"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the magicka recovery proc is ready or when it will be available, but not the durationms of increased magicka recovery.",
        settingsColor = "3A97CF",
        id = 57164,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 60000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/champion/champion_points_magicka_icon-hud.dds",
        showFrame = false,
		durationms = 0,
		stacks = nil,
		},
    ["Vestment of Olorime"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Major Courage area of effect is able to be placed, but does not indicate the duration of Major Courage.",
        settingsColor = "FCFCCB",
        id = {107141, 109084},
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 10000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/placeholder/icon_health_major.dds",
        showFrame = true,
		durationms = 5000,
		stacks = nil,
		},
    ["Steadfast Hero"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Major Protection buff is available through cleansing a negative effect on yourself or an ally.",
        settingsColor = "FCFCCB",
        id = 113509, -- Major Protection
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 12000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_buff_major_protection.dds",
        showFrame = true,
		durationms = 10000,
		stacks = nil,
		},
    ["Caluurion's Legacy"] = {
        procType = "set",
        -- Caluurion Duration = 102060
        -- Disease  = 102033
        -- Fire     = 102027
        -- Shock    = 102034
        -- Ice      = 102032
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the fire, shock, ice, or disease ball proc is ready or when it will be available.",
        settingsColor = "3A97CF",
        id = 102060,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 10000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/death_recap_fire_ranged.dds",
        showFrame = true,
		durationms = 0,
		stacks = nil,
		},
    ["Mechanical Acuity"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Mechanical Acuity proc is ready or when it will be available, but not the duration of the crit bonus.",
        settingsColor = "E100FF",
        id = 99204,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 21000,
        onCooldown = false,
        timeOfProc = 0,
        --texture = "/esoui/art/icons/gear_clockwork_medium_head_a.dds",
        --texture = "/esoui/art/icons/ability_buff_major_sorcery.dds",
        texture = "/esoui/art/icons/ability_rogue_039.dds",
        showFrame = true,
		durationms = 5000,
		stacks = nil,
		},
    ["Crest of Cyrodiil"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the heal on block from Crest of Cyrodiil is ready or when it will become available.",
        settingsColor = "92C843",
        id = 111575,
        enabled = false,
        result = ACTION_RESULT_HEAL,
        cooldownDurationMs = 4000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "esoui/art/icons/placeholder/icon_offensive_shieldsword_01.dds",
        showFrame = true,
		durationms = 0,
		stacks = nil,
		},
     ["Ravager"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when The Ravager weapon damage buff proc is ready or when it will become available.",
        settingsColor = "92C843",
        id = 34872,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 10000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_warrior_012.dds",
        --texture = "/LuiExtended/media/icons/abilities/ability_set_the_ravager.dds",
        showFrame = true,
		duration = 0,
		stacks = nil,
		},
     ["Curse Eater"] = {
        procType = "set",
        event = EVENT_ABILITY_COOLDOWN_UPDATED,
        description = "Displays when the Curse Eater removal of negative effects is ready or when it will become available.",
        settingsColor = "FCFCCB",
        --id = 117359, -- Event
        id = 117360, -- Cooldown
        enabled = false,
        result = ACTION_RESULT_POWER_ENERGIZE,
        cooldownDurationMs = 8000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_ava_005_a.dds",
        showFrame = true,
		duration = 0,
		stacks = nil,
		},
    ["Icy Conjuror"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Ice Wraith proc after applying a minor debuff is ready or when it will become available.",
        settingsColor = "3A97CF",
        id = 117666,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 1000,
        onCooldown = false,
        timeOfProc = 0,
        -- LuiExtended/media/icons/abilities/ability_set_icy_conjuror.dds
        texture = "/esoui/art/icons/death_recap_cold_ranged.dds",
        showFrame = true,
		durationms = 10000,
		stacks = nil,
		},
    ["Hide of the Werewolf"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the ultimate generation from this set is ready or when it will become available.",
        settingsColor = "92C843",
        id = 34508, -- Cooldown
        enabled = false,
        result = ACTION_RESULT_POWER_ENERGIZE,
        cooldownDurationMs = 5000,
        onCooldown = false,
        timeOfProc = 0,
        -- LuiExtended/media/icons/abilities/ability_set_werewolf_hide.dds
        texture = "/esoui/art/icons/ability_werewolf_004_a.dds",
        showFrame = true,
		durationms = 0,
		stacks = nil,
		},
    ["Essence Thief"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the essence pool is ready to be drawn from the enemy or when it will become available.",
        settingsColor = "92C843",
        id = 67324,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 10000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_warrior_012.dds",
        showFrame = true,
		durationms = 10000,
		stacks = nil,
		},
    ["Armor of Truth"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when you are able to gain weapon damage by setting an enemy Off Balance or when it will become available.",
        settingsColor = "92C843",
        id = 86070,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 0,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_debuff_offbalance.dds",
        showFrame = true,
		durationms = 10000,
		stacks = nil,
		},
    ["Claw of Yolnahkriin"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Minor Courage effect is able to be applied, but does not indicate the duration of Minor Courage.",
        settingsColor = "FCFCCB",
        id = 121878,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 8000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/placeholder/icon_health_major.dds",
        showFrame = true,
		durationms = 0,
		stacks = nil,
		},
    ["Seventh Legion Brute"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the added weapon damage and health recovery effect can proc.",
        settingsColor = "FCFCCB",
        id = 127271,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 15000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_warrior_012.dds",
        showFrame = true,
		durationms = 15000,
        stacks = nil,
		},    
    ["Arkasis's Genius"] = {
		procType = "set",
		event = EVENT_COMBAT_EVENT,
		description = "ulti boi",
		settingsColor = "E100FF",
		id = 142660,
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 30000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/esoui/art/icons/consumable_potion_012_type_002.dds",
		showFrame = false,
		durationms = 0,
		stacks = nil,
		},
    ["Roar of Alkosh"] = {
		procType = "set",
		event = EVENT_COMBAT_EVENT,
		description = "Displays when the Alkosh debuff effect is active",
		settingsColor = "E100FF",
		id = 75753,
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 10000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/Cooldowns/icons/alkosh.dds",
		showFrame = true,
		durationms = 0,
		stacks = nil,
		},
	["Hollowfang Thirst"] = {
		procType = "set",
		event = EVENT_COMBAT_EVENT,
		description = "gib mag",
		settingsColor = "E100FF",
		id = 126924,
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 9000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/esoui/art/icons/ability_restorationstaff_003_a.dds",
		showFrame = true,
		durationms = 9000,
		stacks = nil, 
		},
	["Yandir's Might"] = {
 		procType = "set",
 		event = EVENT_COMBAT_EVENT,
 		description = "heavy attack goes brrr",
 		settingsColor = "ff7800",
 		id = 138019,
 		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 15000,
		onCooldown = false,
 		timeOfProc = 0,
		texture = "/esoui/art/icons/ability_warrior_032.dds", 
		showFrame = true,
		durationms = 0,
		stacks = nil,
		},
	["Kyne's Wind"] = {
		procType = "set",
		event = EVENT_COMBAT_EVENT,
		description = "buffy boi",
		settingsColor = "E100FF",
		id = {137995, 136098},
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 10000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/esoui/art/icons/ability_healer_015.dds",
		showFrame = true,
		durationms = 4000,
		stacks = nil,
		},
	["Spell Strategist"] = {
		procType = "set",
		event = EVENT_COMBAT_EVENT,
		description = "light attack goes brrr",
		settingsColor = "ff7800",
		id = 113417,
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 4000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/esoui/art/icons/ability_mage_063.dds",
		showFrame = true,
		durationms = 0,
		stacks = nil,
		},
	["Scavenging Demise"] = {
		procType = "set",
		event = EVENT_COMBAT_EVENT,
		description = "Poison for Vuln Boi.",
		settingsColor = "ff7800",
		id = 116954,
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 15000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/esoui/art/icons/achievement_vvardenfel_005.dds",
		showFrame = true,
		durationms = 10000,
		stacks = nil,
		},
	["Tooth of Lokkestiiz"] = {
 		procType = "set",
 		event = EVENT_COMBAT_EVENT,
 		description = "major slayer.",
 		settingsColor = "ff7800",
 		id = 116954,
 		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 16000,
		onCooldown = false,
 		timeOfProc = 0,
		texture = "/Cooldowns/icons/slayer.dds", 
		showFrame = true,
		durationms = 16000,
		stacks = nil,
		},
	["Livewire"] = {
 		procType = "set",
 		event = EVENT_COMBAT_EVENT,
 		description = "minor vuln goes brr",
 		settingsColor = "ff7800",
 		id = 79717,
 		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 6000,
		onCooldown = false,
 		timeOfProc = 0,
		texture = "esoui/art/icons/death_recap_shock_aoe.dds", 
		showFrame = true,
		durationms = 0,
		stacks = nil,
		},
	["Drake's Rush"] = {
 		procType = "set",
 		event = EVENT_COMBAT_EVENT,
 		description = "bash goes brrr",
 		settingsColor = "E100FF",
 		id = 61709,
 		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 18000,
		onCooldown = false,
 		timeOfProc = 0,
		texture = "/esoui/art/icons/ability_buff_major_heroism.dds", 
		showFrame = true,
		durationms = 12000,
		stacks = nil,
		},
	["Stone-Talker's Oath"] = {
	 	procType = "set",
 		event = EVENT_COMBAT_EVENT,
 		description = "better hollowfang",
 		settingsColor = "E100FF",
 		id = 154783, 
 		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 10000,
		onCooldown = false,
 		timeOfProc = 0,
		texture = "/esoui/art/icons/ability_buff_major_heroism.dds", --edit this maybe use mars id or disease proc--
		showFrame = true,
		durationms = 10000,
		stacks = nil,
		},
    ["Diamond's Victory"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Ranged Supremacy only",
        settingsColor = "E100FF",
        id = {154571, 154560}, 
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 30000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_buff_major_heroism.dds", --edit this--
        showFrame = true,
        durationms = 30000,
        stacks = nil,
        },
------------ Monster Sets ------------
	["Zoal the Ever-Wakeful"] = {
 		procType = "monster",
 		event = EVENT_COMBAT_EVENT,
 		description = "and ur scared",
 		settingsColor = "E100FF",
 		id = 61709, --edit this--
 		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 7000,
		onCooldown = false,
 		timeOfProc = 0,
		texture = "/esoui/art/icons/ability_buff_major_heroism.dds", --edit this--
		showFrame = false,
		durationms = 3000,
		stacks = nil,
		},
	["Immolator Charr"] = {
 		procType = "monster",
 		event = EVENT_COMBAT_EVENT,
 		description = "how tf is this useful",
 		settingsColor = "E100FF",
 		id = 61709, --edit this--
 		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 40000,
		onCooldown = false,
 		timeOfProc = 0,
		texture = "/esoui/art/icons/ability_buff_major_heroism.dds", --edit this--
		showFrame = false,
		durationms = 10000,
		stacks = nil,
		},
    ["Pirate Skeleton"] = {
        procType = "monster",
        event = EVENT_COMBAT_EVENT,
        description = "Weird set goes brrr",
        settingsColor = "CD5031",
        -- This is fucked, why different based on class?
        id = {
            --80501, -- Equipped?
            81675, -- Necro
            83288, -- ?
            83287, -- ?
            98419, -- Templar
            98420, -- ?
            98421, -- Sorcerer?
        },
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 20000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/event_witchfest_sacking_skelet.dds",
        showFrame = true,
        -- texture = "/esoui/art/icons/gear_undauntedpirateskeleton_head_a.dds",
        -- showFrame = false,
	durationms = 15000,
	stacks = nil,
	},
    ["Maarselok"] = {
        procType = "monster",
        event = EVENT_COMBAT_EVENT,
        description = "Bash goes brrr",
        settingsColor = "FCFCCB",
        id = 126941,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 7000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/gear_undmaarselok_helmet_a.dds",
	--this helm also sucks
        showFrame = false,
	durationms = 4000,
	stacks = nil,
	},
    ["Bloodspawn"] = {
        procType = "monster",
        event = EVENT_COMBAT_EVENT,
        description = "ulti boi",
        settingsColor = "CD5031",
        id = 59517,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 5000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/gear_undauntedgargoyle_head_a.dds",
        showFrame = false,
		durationms = 0,
		stacks = nil,
		},
    ["Stonekeeper"] = {
        procType = "monster",
        event = EVENT_COMBAT_EVENT,
        description = "blocky boi",
        settingsColor = "CD5031",
        id = 116877,
        enabled = false,
        result = ACTION_RESULT_POWER_ENERGIZE,
        cooldownDurationMs = 14000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/gear_undauntedstonekeeper_head_a.dds",
        --texture = "/esoui/art/champion/champion_points_health_icon-hud.dds",
        showFrame = false,
	durationms = 0,
	stacks = nil,
	},
     --["Symphony of Blades"] = {
        --procType = "monster",
        --event = EVENT_COMBAT_EVENT,
        --description = "Sustainy boi",
        --settingsColor = "CD5031",
        --id = 117111,
        --enabled = false,
        --result = ACTION_RESULT_EFFECT_GAINED,
        --cooldownDurationMs = 18000,
        --onCooldown = false,
        --timeOfProc = 0,
        --texture = "/esoui/art/icons/gear_undnarlimor_head_a.dds",
        --showFrame = false,
		--duration = 6000,
		--stacks = nil,
		--},
    ["Zaan"] = {
        procType = "monster",
        event = EVENT_COMBAT_EVENT,
        description = "beam goes brrr",
        settingsColor = "3A97CF",
        id = 102136,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 18000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/gear_undaunted_dragonpriest_head_a.dds",
        showFrame = false,
		durationms = 6000,
		-- stacks = true,
		},
    ["Vykosa"] = {
        procType = "monster",
        event = EVENT_COMBAT_EVENT,
        description = "Major Maim goes brr",
        settingsColor = "CD5031",
        id = 111354, -- Major Maim
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 15000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_debuff_major_maim.dds",
        --texture = "/esoui/art/icons/gear_undvykosa_helmet_a.dds",
        showFrame = true,
		durationms = 8000,
		stacks = nil,
		},
    ["Earthgore"] = {
        procType = "monster",
        event = EVENT_COMBAT_EVENT,
        description = "EU healing set",
        settingsColor = "CD5031",
        id = 97855,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 20000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/gear_undaunted_ironatronach_head_a.dds",
        showFrame = false,
		durationms = 10000,
		stacks = nil,
		},
	["Kra'gh"] = {
 		procType = "monster",
 		event = EVENT_COMBAT_EVENT,
 		description = "spikes goes brrr",
 		settingsColor = "ff7800",
 		id = 80566,
 		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 3000,
		onCooldown = false,
 		timeOfProc = 0,
		texture = "/esoui/art/icons/gear_undaunteddreugh_head_a.dds", 
		showFrame = false,
		durationms = 1200,
		stacks = nil,
		},
	["Velidreth"] = {
 		procType = "monster",
 		event = EVENT_COMBAT_EVENT,
 		description = "veli goes brrr",
 		settingsColor = "ff7800",
 		id = 80488,
 		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 8000,
		onCooldown = false,
 		timeOfProc = 0,
		texture = "/esoui/art/icons/gear_undaunted_hoarvordaedra_head_a.dds", 
		showFrame = false,
		durationms = 0,
		stacks = nil,
		},
	["Engine Guardian"] = {
		procType = "monster",
		event = EVENT_COMBAT_EVENT,
		description = "sustainy boi",
		settingsColor = "E100FF",
		id = 59522,
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 10000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/esoui/art/icons/gear_undaunteddwemer_head_a.dds",
		showFrame = false,
		durationms = 6000,
		stacks = nil,
		},
	["Lord Warden"] = {
		procType = "monster",
		event = EVENT_COMBAT_EVENT,
		description = "buffy boi",
		settingsColor = "E100FF",
		id = 59587,
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 10000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/esoui/art/icons/gear_undauntedgrievoust_head_a.dds",
		showFrame = false,
		durationms = 0,
		stacks = nil,
		},
	["Ilambris"] = {
		procType = "monster",
		event = EVENT_COMBAT_EVENT,
		description = "twin Boi",
		settingsColor = "E100FF",
		id = {80527, 80529},
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 8000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/esoui/art/icons/gear_undauntedxivilai_head_a.dds",
		showFrame = false,
		durationms = 5000,
		stacks = nil,
		},
	["Maw of the Infernal"] = {
		procType = "monster",
		event = EVENT_COMBAT_EVENT,
		description = "Daedroth boi",
		settingsColor = "E100FF",
		id = 59508,
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 15000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/esoui/art/icons/gear_undaunted_daedroth_head_a.dds",
		showFrame = false,
		durationms = 15000,
		stacks = nil,
		},
	["Iceheart"] = {
		procType = "monster",
		event = EVENT_COMBAT_EVENT,
		description = "shield boi",
		settingsColor = "E100FF",
		id = 80562,
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 6000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/esoui/art/icons/gear_undauntedatronach_head_a.dds",
		showFrame = false,
		durationms = 6000,
		stacks = nil,
		},
	["Balorgh"] = {
		procType = "monster",
		event = EVENT_COMBAT_EVENT,
		description = "burst goes brrrr",
		settingsColor = "E100FF",
		id = 111505,
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 12000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/esoui/art/icons/gear_undaunted_werewolfbehemoth_head_a.dds",
		showFrame = false,
		durationms = 0,
		stacks = nil,
		},
	["Grothdarr"] = {
		procType = "monster",
		event = EVENT_COMBAT_EVENT,
		description = "ringy Boi",
		settingsColor = "E100FF",
		id = 84504,
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 10000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/esoui/art/icons/gear_undauntedfleshatronach_head_a.dds",
		showFrame = false,
		durationms = 5000,
		stacks = nil,
		},
    ["Lady Thorn"] = {
        procType = "monster",
        event = EVENT_COMBAT_EVENT,
        description = "synergy boi",
        settingsColor = "E100FF",
        id = 141905,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 10000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/gear_undvamplord_head_a.dds",
        showFrame = false,
        durationms = 0,
        stacks = nil,
		},
    ["Valkyn Skoria"] = {
        procType = "monster",
		event = EVENT_COMBAT_EVENT,
		description = "meteor boi",
		settingsColor = "E100FF",
		id = 59596,
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 5000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/esoui/art/icons/gear_undaunted_magma_head_a.dds",
		showFrame = false,
		durationms = 0,
		stacks = nil,
		},
	["Tremorscale"] = {
	    procType = "monster",
	    event = EVENT_COMBAT_EVENT,
	    description = "taunt goes brrr",
	    settingsColor = "CD5031",
	    id = 80866,
	    enabled = false,
	    result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 8000,
		onCooldown = false,
	    timeOfProc = 0,
	    texture = "/esoui/art/icons/gear_undauntedsuneripper_head_a.dds",
	    showFrame = false,
	    durationms = 8000,
	    stacks = nil,
		},
	["Domihaus"] = {
	    procType = "monster",
	    event = EVENT_COMBAT_EVENT,
	    description = "ring goes brrr",
	    settingsColor = "df4242",
	    id = 152673,
	    enabled = false,
	    result = ACTION_RESULT_EFFECT_GAINED_DURATION,
	    cooldownDurationMs = 15000,
	    onCooldown = false,
	    timeOfProc = 0,
	    texture = "/esoui/art/icons/gear_undauntedminotaur_a.dds",
	    showFrame = false,
	    durationms = 10000,
	    stacks = nil,
		},
    ["Encratis's Behemoth"] = {
        procType = "monster",
        event = EVENT_COMBAT_EVENT,
        description = "tank domi",
        settingsColor = "df4242",
        id = 151032,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED_DURATION,
        cooldownDurationMs = 15000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/death_recap_fire_dot_heavy.dds",
        showFrame = true,
        durationms = 10000,
        stacks = nil,
        },
    ["Sentinel of Rkugamz"] = {
        procType = "monster",
        event = EVENT_COMBAT_EVENT,
        description = "healer domi",
        settingsColor = "df4242",
        id = 81036,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED_DURATION,
        cooldownDurationMs = 15000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/gear_undauntedcenturion_head_a.dds",
        showFrame = true,
        durationms = 8000,
        stacks = nil,
        },
------------ Arena Sets ------------
	["Void Bash"] = {
 		procType = "arena",
 		event = EVENT_COMBAT_EVENT,
 		description = "power bash goes brrr",
 		settingsColor = "E100FF",
 		id = 147747,
 		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 13000,
		onCooldown = false,
 		timeOfProc = 0,
		texture = "/esoui/art/icons/gear_voidrot_shield_a.dds", 
		showFrame = false,
		durationms = 13000,
		stacks = nil,
		},
    ["Destructive Impact"] = {
        procType = "arena",
		event = EVENT_COMBAT_EVENT,
		description = "masters Staff",
		settingsColor = "E100FF",
		id = 140334,
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 4000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/esoui/art/icons/ability_mage_023.dds",
		showFrame = true,
		durationms = 4000,
		stacks = nil,
		},
    ["Wrath of Elements"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "Proctard go boom",
        settingsColor = "E100FF",
        id = 147843,
       enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 10000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/gear_reachv2_staff_a.dds",
        showFrame = false,
        durationms = 10000,
        stacks = nil,
        },
    ["Force Overflow"] = {
        procType = "set",
        event = EVENT_COMBAT_EVENT,
        description = "buffy boi",
        settingsColor = "E100FF",
        id = 147872,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 10000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/gear_reachv2_staff_a.dds",
        showFrame = false,
        durationms = 10000,
        stacks = nil,
        },
------------ Synergies ------------
    ["Orbs / Shards"] = {
        procType = "synergy",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Undaunted orb or Templar shard synergy is able to be used or when it will become available.",
        settingsColor = "FCFCCB",
        id = {108799, 108802, 108821, 108924},
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 20000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_undaunted_004b.dds",
        showFrame = true,
        durationms = 0,
        stacks = nil,
		},
    ["Conduit"] = {
        procType = "synergy",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Conduit synergy from the Sorcerer Lightning Splash ability is able to be used or when it will become available.",
        settingsColor = "3A97CF",
        id = 108607,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 20000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_sorcerer_liquid_lightning.dds",
        showFrame = true,
        durationms = 0,
        stacks = nil,
		},
    ["Purify"] = {
        procType = "synergy",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Purify synergy from the Templar Cleansing Ritual ability is able to be used or when it will become available.",
        settingsColor = "FCFCCB",
        id = 108824,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 20000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_templar_extended_ritual.dds",
        showFrame = true,
        durationms = 0,
        stacks = nil,
		},
    ["Bone Shield"] = {
        procType = "synergy",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Undaunted Bone Wall/Bone Shield synergy is able to be used or when it will become available.",
        settingsColor = "92C843",
        id = {108794, 108797},
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 20000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_undaunted_005.dds",
        showFrame = true,
        durationms = 6000,
        stacks = nil,
		},
    ["Blood Altar"] = {
        procType = "synergy",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Undaunted Blood Altar/Overflowing Altar synergy is able to be used or when it will become available.",
        settingsColor = "CD5031",
        id = {108782, 108787},
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 20000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_undaunted_001_b.dds",
        showFrame = true,
        durationms = 0,
        stacks = nil,
		},
    ["Harvest"] = {
        procType = "synergy",
        -- Thanks to Liofa for patching and testing for this synergy
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Warden Healing Seed synergy is able to be used or when it will become available.",
        settingsColor = "CD5031",
        id = 108826,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 20000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_warden_007.dds",
        showFrame = true,
        durationms = 5000,
        stacks = nil,
		},
    ["Grave Robber"] = {
        procType = "synergy",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Grave Robber synergy from the Necromancer Avid Boneyard ability is able to be used or when it will become available.",
        settingsColor = "3A97CF",
        id = {115567, 115571},
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 20000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_necromancer_004_b.dds",
        showFrame = true,
        durationms = 0,
        stacks = nil,
		},
    ["Pure Agony"] = {
        procType = "synergy",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Pure Agony synergy from the Necromancer Agony Totem ability is able to be used or when it will become available.",
        settingsColor = "3A97CF",
        id = {118610, 118606},
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 20000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_necromancer_010_b.dds",
        showFrame = true,
        durationms = 5000,
        stacks = nil,
		},
    ["Black Widows"] = {
        procType = "synergy",
        event = EVENT_COMBAT_EVENT,
        description = "Displays when the Black Widows synergy from the Undaunted Trapping Webs ability is able to be used or when it will become available.",
        settingsColor = "92C843",
        id = {108766, 108791, 108792},
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 20000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_undaunted_003_b.dds",
        showFrame = true,
        durationms = 10000,
        stacks = nil,
    },
    ["Sanguine Burst"] = {
		procType = "synergy",
		event = EVENT_COMBAT_EVENT,
		description = "Displays when the Lady Thorn synergy is available.",
		settingsColor = "E100FF",
		id = {142307},
		enabled = false,
		result = ACTION_RESULT_EFFECT_GAINED,
		cooldownDurationMs = 20000,
		onCooldown = false,
		timeOfProc = 0,
		texture = "/esoui/art/icons/ability_u23_bloodball_chokeonit.dds",
		showFrame = true,
		durationms = 8000,
		stacks = nil,
		},
------------ Passives ------------
    -- UnitClassId
    -- 1: Dragonknight
    -- 2: Sorcerer
    -- 3: Nightblade
    -- 4: Warden
    -- 5: Necromancer
    -- 6: Templar
    ["Corpse Consumption"] = {
        procType = "passive",
        classId = 5,
        event = EVENT_COMBAT_EVENT,
        description = "Displays the cooldown for gaining ultimate when using an ability on a corpse.",
        settingsColor = "CD5031",
        id = 120612,
        enabled = false,
        result = ACTION_RESULT_POWER_ENERGIZE,
        cooldownDurationMs = 16000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/passive_necromancer_011.dds",
        showFrame = true,
        durationms = 0,
        stacks = nil,
		},
    ["Prism"] = {
        procType = "passive",
        classId = 6,
        event = EVENT_COMBAT_EVENT,
        description = "Displays the cooldown for gaining ultimate when using a Dawn's Wrath ability.",
        settingsColor = "CD5031",
        id = 45217,
        enabled = false,
        result = ACTION_RESULT_POWER_ENERGIZE,
        cooldownDurationMs = 6000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/passive_templar_030.dds",
        showFrame = true,
        durationms = 0,
        stacks = nil,
		},
    ["Mountain's Blessing"] = {
        procType = "passive",
        classId = 1,
        event = EVENT_COMBAT_EVENT,
        description = "Displays the cooldown for gaining ultimate by using an Eathern Heart ability while in combat. Does not reflect the Minor Brutality portion of this passive.",
        settingsColor = "CD5031",
        id = 45005,
        enabled = false,
        result = ACTION_RESULT_POWER_ENERGIZE,
        cooldownDurationMs = 6000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/passive_dragonknight_020.dds",
        showFrame = true,
        durationms = 0,
        stacks = nil,
		},
    ["Transfer"] = {
        procType = "passive",
        classId = 3,
        event = EVENT_COMBAT_EVENT,
        description = "Displays the cooldown for gaining ultimate upon activating a Siphoning ability.",
        settingsColor = "CD5031",
        id = 45146,
        enabled = false,
        result = ACTION_RESULT_POWER_ENERGIZE,
        cooldownDurationMs = 4000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/passive_sorcerer_002.dds",
        showFrame = true,
        durationms = 0,
        stacks = nil,
		},
    ["Savage Beast"] = {
        procType = "passive",
        classId = 4,
        event = EVENT_COMBAT_EVENT,
        description = "Displays the cooldown for gaining ultimate upon activating an Animal Companion ability.",
        settingsColor = "CD5031",
        id = 88513,
        enabled = false,
        result = ACTION_RESULT_POWER_ENERGIZE,
        cooldownDurationMs = 8000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/passive_warden_009.dds",
        showFrame = true,
        durationms = 0,
        stacks = nil,
		},
    ["Exploitation"] = {
        procType = "passive",
        classId = 2,
        event = EVENT_COMBAT_EVENT,
        description = "Displays the duration on Minor Prophecy.",
        settingsColor = "CD5031",
        id = 61691,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 20000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_sorcerer_039.dds",
        showFrame = true,
        durationms = 0,
        stacks = nil,
		},
	["Sub Assault"] = {
        procType = "passive",
        classId = 4,
        event = EVENT_COMBAT_EVENT,
        description = "shalks.",
        settingsColor = "CD5031",
        id = 86019,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 0,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_warden_015_b.dds",
        showFrame = false,
		durationms = 6000,
		stacks = nil,
		},
------------ Enchants ------------
    ["Berserker"] = {
        procType = "enchant",
        event = EVENT_COMBAT_EVENT,
        description = "weapon damage goes brrr",
        settingsColor = "E100FF",
        id = 21230,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 5000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ava_artifact_006.dds",
        showFrame = true,
        durationms = 0,
        stacks = nil,
        },
	["Crusher"] = {
        procType = "enchant",
        event = EVENT_COMBAT_EVENT,
        description = "crusher goes brrr",
        settingsColor = "E100FF",
        id = 17906,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 5000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ava_artifact_004.dds",
        showFrame = true,
		durationms = 0,
		stacks = nil,
		},
------------ CP Passives ------------
     ["Slippery"] = {
        procType = "cp",
        event = EVENT_COMBAT_EVENT,
        description = "slippery goes brrr",
        settingsColor = "E100FF",
        id = 134254,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 21000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_debuff_stun.dds",
        showFrame = true,
		durationms = 7000,
		stacks = nil,
		},
    ["Expert Evasion"] = {
        procType = "cp",
        event = EVENT_COMBAT_EVENT,
        description = "free roll goes brrr",
        settingsColor = "E100FF",
        id = 151113,
        enabled = false,
        result = ACTION_RESULT_EFFECT_GAINED,
        cooldownDurationMs = 30000,
        onCooldown = false,
        timeOfProc = 0,
        texture = "/esoui/art/icons/ability_healer_009.dds",
        showFrame = true,
        durationms = 0,
        stacks = nil,
        },
}
-- These two tables work together
-- to map item slot constants to
-- human-readable names.
-- Why two tables? Good question.
Cool.Data.ITEM_SLOTS = {
    EQUIP_SLOT_HEAD,
    EQUIP_SLOT_NECK,
    EQUIP_SLOT_CHEST,
    EQUIP_SLOT_SHOULDERS,
    EQUIP_SLOT_MAIN_HAND,
    EQUIP_SLOT_OFF_HAND,
    EQUIP_SLOT_WAIST,
    EQUIP_SLOT_LEGS,
    EQUIP_SLOT_FEET,
    EQUIP_SLOT_RING1,
    EQUIP_SLOT_RING2,
    EQUIP_SLOT_HAND,
    EQUIP_SLOT_BACKUP_MAIN,
    EQUIP_SLOT_BACKUP_OFF,
}
Cool.Data.ITEM_SLOT_NAMES = {
    "Head",
    "Neck",
    "Chest",
    "Shoulders",
    "Main-Hand Weapon",
    "Off-Hand Weapon",
    "Waist",
    "Legs",
    "Feet",
    "Ring 1",
    "Ring 2",
    "Hands",
    "Backup Main-Hand Weapon",
    "Backup Off-Hand Weapon",
}
